### ISSUE TITLE
当环境变量 `NEMU_HOME` 为空时，自动日志记录无法正确工作。

### ISSUE THREAD

**Issue by Arielfoever** [OSCPU/ysyx-workbench#21]
环境： Ubuntu 24.04 LTS

问题似乎出现在 https://github.com/OSCPU/ysyx-workbench/blob/c074ba47c5fc6744c8f11fb583ab7488b50e4756/Makefile#L23 

运行下列命令：

```
cd ysyx-workbench
bash init.sh npc
cd npc
make sim
```

获得如下内容。

```
flock: 不能打开锁文件 /../.git/: 没有那个文件或目录
make: [Makefile:5：sim] 错误 66 (已忽略）
sync: 打开 '/../.git/' 时出错: 没有那个文件或目录
make: [Makefile:5：sim] 错误 1 (已忽略）
Write this Makefile by your self.
verilator --trace-fst -cc --exe --build -j vsrc/example.v csrc/main.cpp
make[1]: 进入目录“/home/ariel/ysyx-workbench/npc/obj_dir”
make[1]: 对“default”无需做任何事。
make[1]: 离开目录“/home/ariel/ysyx-workbench/npc/obj_dir”
- V e r i l a t i o n   R e p o r t: Verilator 5.029 devel rev UNKNOWN.REV
- Verilator: Built from 0.000 MB sources in 0 modules, into 0.000 MB in 0 C++ files needing 0.000 MB
- Verilator: Walltime 0.014 s (elab=0.000, cvt=0.000, bld=0.009); cpu 0.001 s on 0 threads; alloced 18.445 MB
```

~~我猜想调试外部的自动日志工具不属于预学习阶段的内容。~~

**Comment by Wenz-jam** [comment]
一生一芯预学习阶段 `Linux系统安装和基本使用` 要求你根据PA0安装linux操作系统 其中 `Getting Source Code for PAs`
部分在bash环境下会自动设置NEMU_HOME的环境变量.  
而bash环境下应用设置的指令也在下方给出:   

> source ~/.bashrc  

 文中也提到如果你使用的是别的shell环境,请自行添加环境变量  

> Particularly, if you use shell other than bash, please set these variables in the corresponding configuration file manually.  

之后也要求你检查环境变量是否正确设置: 
> to check whether these environment variables get the right paths. If both the echo commands report the right paths, and both the cd command change to the target paths without errors, we are done. If not, please double check the steps above and the shell you are using.

你是否跳过了这些步骤呢?如果没有跳过这些步骤,为什么NEMU_HOME会没有被正确的设置呢?  

更进一步的,nemu会在编译的时候检查NEMU_HOME有没有被正确设置
```makefile
# Sanity check
ifeq ($(wildcard $(NEMU_HOME)/src/nemu-main.c),)
  $(error NEMU_HOME=$(NEMU_HOME) is not a NEMU repo)
endif
```  
而你提到的YSYX_HOME是由NEMU_HOME设置的:  
```makefile
YSYX_HOME = $(NEMU_HOME)/..
```  
你也可以参照nemu的设置, 修改npc的makefile,在NEMU_HOME或者YSYX_HOME没有被正确设置的情况下终止编译过程  

另外的,我注意到你的verilator的版本是5.029, 而讲义中推荐的版本是5.008  
> 此外, 为了统一版本, 你需要通过git安装5.008的版本. 

# 如何科学地提问是预学习的第一课

**Comment by Arielfoever** [comment]
Closed Due To NOT PLANNED.

我相信是因为我假设了这几个预学习阶段的页面相互独立。

另外的，我注意到我的 Verilator 的版本是 5.029 因为学校的指示是 `5.027 or newer`。
